package Q1;

public class Book extends Publication {
	
	String author;
	
	//constructor
	public Book(String publishers, int pages, int prices, String titles,String author) {
		super(publishers,pages,prices,titles);
		this.author=author;
	}

	//getter
	public String getAuthor() {
		return author;
	}
	
	//setter
	public void setAuthor() {
		this.author= author;
	}
	
	//output method
		public String publication_info() {
			return super.toString()  + "Author:"+ this.author;
			//plus author
		}
		
}


//design a class hierarchy consisting of publication, magazine,book, and kidsmagazine classes.
//The publication class has fields that store publishers, pages, prices and titles, and must implement and output method that displays all of these information.
//The magazine class is a type of publication that has additional information on the publicaion cycle(monthly,weekly,biweekly,etc).
//Magazine must override the output method of Publication and this method must display all magazine information including the added new information.
//the book class is a type of publication that has additional information on the author information.
//book should also override the output method of Publication.
//the kidsmagazine class is a type of magazine that has additional recommended age rage information.
//kidsmagazine should also override the output method of publication
//All four classes above should include getter and setter methods for each field
//all four classes above must contain a default constructor and a constructor capable of initializing all fields.
//implement a PublicationTest class that includes a main() method that stores 10 objects generated by receiving data of the above four types of objects evenly(Publication,magazine,book,kidsmagazine) in a publication type array and output object information by arranging the four types of objects stored in the array in descending order based on the title.







